name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get -y install \
          gettext \
          libgtk-3-dev \
          libgtk-4-dev \
          libcurl4-openssl-dev \
          meson \
          language-pack-en \
          python3.10 \
          liblzma-dev \
          libicu-dev \
          libsqlite3-dev \
          qt6-base-dev \
          libsdl2-mixer-dev \
          libsdl2-gfx-dev \
          libsdl2-image-dev \
          libsdl2-ttf-dev \
          libmysqlclient-dev \
          unixodbc-dev
    - name: build
      shell: bash
      run: ./scripts/ci-build.sh meson

    - name: test
      shell: bash
      run: ./tests/src-check.sh

    - name: achvive
      shell: bash
      run: tar -czvf freeciv-server.tar.gz ./build/freeciv-server ./build/libfreeciv.so ./data/
      
    - name: artifact
      uses: actions/upload-artifact@v4
      with:
        name: tar
        path: ./*tar.gz
    
    
